# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compete', '0001_initial'),
        ('physical_object', '0001_initial'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified time')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active'), ('Closed', 'Closed'), ('Tentative', 'Tentative'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Active', max_length=100)),
                ('priority', models.IntegerField(default=0)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('xpos', models.IntegerField(blank=True, null=True)),
                ('ypos', models.IntegerField(blank=True, null=True)),
                ('zpos', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(default=1)),
                ('lap_number', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('gap', models.DurationField(blank=True, null=True)),
                ('race_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('fixture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compete.Fixture')),
                ('method', models.CharField(choices=[('laps', 'laps'), ('duration', 'duration'), ('duration', 'laps or duration')], default='laps', max_length=100)),
                ('total_laps', models.IntegerField(blank=True, null=True)),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('current_lap_number', models.IntegerField(blank=True, null=True)),
                ('laps_to_go', models.IntegerField(blank=True, null=True)),
                ('time_to_go', models.DurationField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('compete.fixture',),
        ),
        migrations.CreateModel(
            name='RaceCar',
            fields=[
                ('vehicle_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='physical_object.Vehicle')),
                ('car_id_txt', models.CharField(max_length=10)),
                ('sponsor', models.CharField(blank=True, max_length=200)),
                ('tyres', models.CharField(blank=True, max_length=100)),
                ('colours', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('physical_object.vehicle',),
        ),
        migrations.CreateModel(
            name='RaceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sponsor', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compete.Entry')),
                ('timing_id', models.IntegerField(blank=True, null=True)),
                ('car_id_txt', models.CharField(blank=True, max_length=10, null=True)),
                ('grid_pos', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('finish_pos', models.IntegerField(blank=True, null=True)),
                ('finish_time', models.TimeField(blank=True, null=True)),
                ('current_driver', models.IntegerField(default=0)),
                ('current_position', models.IntegerField(blank=True, null=True)),
                ('current_points', models.IntegerField(blank=True, null=True)),
                ('current_gap', models.DurationField(blank=True, null=True)),
                ('current_time', models.DurationField(blank=True, null=True)),
                ('best_lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_entry_best_lap', to='motorsport.Lap')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motorsport.RaceCar')),
                ('codriver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codriver', to='party.Individual')),
                ('current_lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_entry_current_lap', to='motorsport.Lap')),
                ('last_lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='race_entry_last_lap', to='motorsport.Lap')),
                ('race_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motorsport.RaceClass')),
            ],
            options={
                'abstract': False,
            },
            bases=('compete.entry',),
        ),
        migrations.AddField(
            model_name='racecar',
            name='race_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motorsport.RaceClass'),
        ),
        migrations.AddField(
            model_name='race',
            name='race_classes',
            field=models.ManyToManyField(blank=True, to='motorsport.RaceClass'),
        ),
        migrations.AddField(
            model_name='lap',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compete.Entry'),
        ),
        migrations.AddField(
            model_name='lap',
            name='fixture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete.Fixture'),
        ),
        migrations.AddField(
            model_name='lap',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compete.EventTemplate'),
        ),
    ]
